project_id = "bxmokisoyslsoigpcilc"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.generate-invoice-pdf]
verify_jwt = false

[functions.check-rate-limit]
verify_jwt = false