project_id = "bxmokisoyslsoigpcilc"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false